[package]
name = "day_14"
version = "0.2.0"
authors = ["Raphael Bost <raphael_bost@alumni.brown.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"